name: Checklist Progress Badge

on:
  workflow_dispatch:
  push:
    paths:
      - "langs/*.md"
jobs:
  push:
    name: NFR documents changed
    runs-on: ubuntu-latest
    steps:
      - name: Checklist Progress Badge
        uses: dodopizza/gha-checklist-badges@v0.1
        with:
          fetch-depth: 0
      - name: Update NFR badges
        uses: ./.
        with:
          readme-fname: README.md
          nfr-fnames: langs/en.md langs/ch.md langs/fr.md langs/jp.md langs/ru.md
          github_token: ${{ secrets.GITHUB_TOKEN }}
